// <auto-generated />
using System;
using DonationSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DonationSystem.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DonationSystem.Core.Models.Entities.Distribution", b =>
                {
                    b.Property<int>("DistributionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DistributionId"));

                    b.Property<string>("Complaint")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("DonationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GivenDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ItemId")
                        .HasColumnType("integer");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OfficerId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer");

                    b.HasKey("DistributionId");

                    b.HasIndex("DonationId");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.HasIndex("OfficerId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("Distributions");
                });

            modelBuilder.Entity("DonationSystem.Core.Models.Entities.Donation", b =>
                {
                    b.Property<int>("DonationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DonationId"));

                    b.Property<DateTime>("DonatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DonorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OfficerId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("DonationId");

                    b.HasIndex("DonorId");

                    b.HasIndex("OfficerId");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("DonationSystem.Core.Models.Entities.Donor", b =>
                {
                    b.Property<int>("DonorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DonorId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NICNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("DonorId");

                    b.HasIndex("NICNumber")
                        .IsUnique();

                    b.ToTable("Donors");
                });

            modelBuilder.Entity("DonationSystem.Core.Models.Entities.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<int?>("DonationId")
                        .HasColumnType("integer");

                    b.Property<int?>("DonorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int?>("ReceiverId")
                        .HasColumnType("integer");

                    b.HasKey("ItemId");

                    b.HasIndex("DonationId");

                    b.HasIndex("DonorId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("DonationSystem.Core.Models.Entities.Officer", b =>
                {
                    b.Property<int>("OfficerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OfficerId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("NICNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OfficeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Post")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("OfficerId");

                    b.HasIndex("NICNumber")
                        .IsUnique();

                    b.ToTable("Officers");
                });

            modelBuilder.Entity("DonationSystem.Core.Models.Entities.Receiver", b =>
                {
                    b.Property<int>("ReceiverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReceiverId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.HasKey("ReceiverId");

                    b.ToTable("Receivers");
                });

            modelBuilder.Entity("DonationSystem.Core.Models.Entities.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RouteId"));

                    b.Property<decimal>("Distance")
                        .HasColumnType("numeric");

                    b.Property<int>("DistributionId")
                        .HasColumnType("integer");

                    b.Property<int>("FromOfficerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ToReceiverId")
                        .HasColumnType("integer");

                    b.HasKey("RouteId");

                    b.HasIndex("DistributionId");

                    b.HasIndex("FromOfficerId");

                    b.HasIndex("ToReceiverId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("DonationSystem.Core.Models.Entities.Distribution", b =>
                {
                    b.HasOne("DonationSystem.Core.Models.Entities.Donation", "Donation")
                        .WithMany("Distributions")
                        .HasForeignKey("DonationId");

                    b.HasOne("DonationSystem.Core.Models.Entities.Item", "Item")
                        .WithOne()
                        .HasForeignKey("DonationSystem.Core.Models.Entities.Distribution", "ItemId");

                    b.HasOne("DonationSystem.Core.Models.Entities.Officer", "Officer")
                        .WithMany("Distributions")
                        .HasForeignKey("OfficerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DonationSystem.Core.Models.Entities.Receiver", "Receiver")
                        .WithMany("Distributions")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donation");

                    b.Navigation("Item");

                    b.Navigation("Officer");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("DonationSystem.Core.Models.Entities.Donation", b =>
                {
                    b.HasOne("DonationSystem.Core.Models.Entities.Donor", "Donor")
                        .WithMany("Donations")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DonationSystem.Core.Models.Entities.Officer", "Officer")
                        .WithMany("Donations")
                        .HasForeignKey("OfficerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Donor");

                    b.Navigation("Officer");
                });

            modelBuilder.Entity("DonationSystem.Core.Models.Entities.Item", b =>
                {
                    b.HasOne("DonationSystem.Core.Models.Entities.Donation", "Donation")
                        .WithMany("Items")
                        .HasForeignKey("DonationId");

                    b.HasOne("DonationSystem.Core.Models.Entities.Donor", "Donor")
                        .WithMany("Items")
                        .HasForeignKey("DonorId");

                    b.HasOne("DonationSystem.Core.Models.Entities.Receiver", "Receiver")
                        .WithMany("Items")
                        .HasForeignKey("ReceiverId");

                    b.Navigation("Donation");

                    b.Navigation("Donor");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("DonationSystem.Core.Models.Entities.Route", b =>
                {
                    b.HasOne("DonationSystem.Core.Models.Entities.Distribution", "Distribution")
                        .WithMany("Routes")
                        .HasForeignKey("DistributionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DonationSystem.Core.Models.Entities.Officer", "FromOfficer")
                        .WithMany()
                        .HasForeignKey("FromOfficerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DonationSystem.Core.Models.Entities.Receiver", "ToReceiver")
                        .WithMany()
                        .HasForeignKey("ToReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distribution");

                    b.Navigation("FromOfficer");

                    b.Navigation("ToReceiver");
                });

            modelBuilder.Entity("DonationSystem.Core.Models.Entities.Distribution", b =>
                {
                    b.Navigation("Routes");
                });

            modelBuilder.Entity("DonationSystem.Core.Models.Entities.Donation", b =>
                {
                    b.Navigation("Distributions");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("DonationSystem.Core.Models.Entities.Donor", b =>
                {
                    b.Navigation("Donations");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("DonationSystem.Core.Models.Entities.Officer", b =>
                {
                    b.Navigation("Distributions");

                    b.Navigation("Donations");
                });

            modelBuilder.Entity("DonationSystem.Core.Models.Entities.Receiver", b =>
                {
                    b.Navigation("Distributions");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
